import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // PasarGo design system — exact from Stitch
        'primary': '#006b2d',
        'on-primary': '#ffffff',
        'primary-container': '#00873b',
        'on-primary-container': '#f7fff3',
        'primary-fixed': '#85fb9c',
        'primary-fixed-dim': '#69de82',
        'on-primary-fixed': '#002109',
        'on-primary-fixed-variant': '#005322',
        'inverse-primary': '#69de82',
        'secondary': '#835400',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffae2c',
        'on-secondary-container': '#6c4500',
        'secondary-fixed': '#ffddb5',
        'secondary-fixed-dim': '#ffb956',
        'on-secondary-fixed': '#2a1800',
        'on-secondary-fixed-variant': '#643f00',
        'tertiary': '#0051d4',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#2169fd',
        'on-tertiary-container': '#fefcff',
        'tertiary-fixed': '#dbe1ff',
        'tertiary-fixed-dim': '#b3c5ff',
        'on-tertiary-fixed': '#00174a',
        'on-tertiary-fixed-variant': '#003ea6',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f2fcf2',
        'surface-dim': '#d2ddd3',
        'surface-bright': '#f2fcf2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#ecf6ec',
        'surface-container': '#e6f1e7',
        'surface-container-high': '#e1ebe1',
        'surface-container-highest': '#dbe5db',
        'surface-variant': '#dbe5db',
        'surface-tint': '#006e2f',
        'surface-white': '#FFFFFF',
        'on-surface': '#151e18',
        'on-surface-variant': '#3e4a3e',
        'inverse-surface': '#29332c',
        'inverse-on-surface': '#e9f3e9',
        'outline': '#6e7a6d',
        'outline-variant': '#bdcaba',
        'background': '#f2fcf2',
        'on-background': '#151e18',
        'fresh-green-dark': '#0B6B31',
        'background-off-white': '#F5F7F4',
        'border-muted': '#DFE7E1',
        'text-secondary': '#66736B',
        // Status colors
        'status-placed': '#246BFE',
        'status-reviewing': '#F6A623',
        'status-packing': '#915BFF',
        'status-ready': '#159947',
        'status-delivery': '#0B6B31',
        'status-done': '#17201A',
        'status-canceled': '#D64545',
      },
      fontFamily: {
        'display': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline': ['"Plus Jakarta Sans"', 'sans-serif'],
        'sans': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'badge-cap': ['12px', { lineHeight: '1', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['13px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'title-md': ['18px', { lineHeight: '1.5', fontWeight: '600' }],
      },
      spacing: {
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'base': '4px',
        'gutter': '16px',
        'margin-mobile': '18px',
        'margin-desktop': '32px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'card': '0px 4px 12px rgba(20, 40, 28, 0.04)',
        'header': '0px 4px 12px rgba(20, 40, 28, 0.08)',
        'btn-primary': '0px 8px 20px rgba(0, 107, 45, 0.25)',
        'bottom-nav': '0px -4px 12px rgba(20, 40, 28, 0.04)',
      },
    },
  },
  plugins: [],
}

export default config
